Lecture 5
Stuard256/phoneshop-servlet-api pull request #7
Opened 2021-03-02 15:03 UTC by Stuard256

2021-03-02 16:19 UTC, alexandr-i requested changes
Написал бы ещё, но начни с этого.
Проверь всё таки критериии которые я присылал там много ещё чего можно доделать

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/entity/Order.java
> +    private Long id;
воу воу

что за каша, поля потом методы

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/entity/Order.java
> +    public Order() {
кому подарочек такой?

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/exception/ProductNotFoundException.java
> +    public ProductNotFoundException(){}
кому пишем дефолтные конструкторы?

и что за импорт лишний?

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/service/DefaultOrderService.java
> +        } catch (NullPointerException e) {
что за магическая логика?

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/service/OrderService.java
> +    Map<String,String> validate(Order order, String firstName, String lastName, String phone, String deliveryDate, String deliveryAdress, String paymentMethod);
маловато параметров, давай штук 30)

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/CheckoutPageServlet.java
> +        } else
опять скобок жалеешь?

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/service/DefaultOrderService.java
> +    public Map<String, String> validate(Order order, String firstName, String lastName, String phone, String deliveryDate, String deliveryAdress, String paymentMethod) {
метод огонь.
вижу мест 5 для рефакторинга и укорачивания раз в 8

И вообще на мой взгляд есть проблемы с зонами ответственности
У тебя сервис вроде как занимается сейчас валидацией и сохранением и тд при внешних вызовах.
Если валидация из контроллера то хорошо бы иметь одтельный слой "валидатор"
Или если  хочешь делать в сервисе, то тогда пусть валидация будет приватной часть сохранения.
и ерроры мапу можно запихнуть в эксепшен который ловить на контроллере. в общем вариантов хватает, но нужно чётенько.

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/service/OrderService.java
> +    Map<String,String> validate(Order order, String firstName, String lastName, String phone, String deliveryDate, String deliveryAdress, String paymentMethod);
если переделаешь по комменту в сервисе то тут и не нужен этот метод

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ErrorHandler.java
> +    static public void handle(HttpServletRequest request, HttpServletResponse response, Exception e) throws ServletException, IOException {
а что instance of отменили уже?

+ где else или может несколько условий пройти?

вообще вагную что если бы проет был реальным через год тут бы было 35+ if
такие штуки делают через map хендлеров

но тогда придёться делать синглетон,.....

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        }catch (ProductNotFoundException e) {
форматирование

2021-03-02 16:19 UTC, alexandr-i commented on src/main/webapp/WEB-INF/pages/overview.jsp
> +    <tr>
таг?

2021-03-02 16:19 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/web/OrderOverviewPageServlet.java
> +            if (orderDao.getOrder(id) == null) {
вот в дао вместо .orElse(null) должен кидаться эксепшен а эти проверки в сервисе совсем печаль

то же самое и в продуктовом

2021-03-02 18:39 UTC, Stuard256 commented on src/main/java/com/es/phoneshop/model/product/entity/Order.java
> +    private Long id;
исправил

2021-03-02 18:40 UTC, Stuard256 commented on src/main/java/com/es/phoneshop/model/product/entity/Order.java
> +    public Order() {
исправил

2021-03-02 18:40 UTC, Stuard256 commented on src/main/java/com/es/phoneshop/model/product/exception/ProductNotFoundException.java
> +    public ProductNotFoundException(){}
исправлено

2021-03-02 18:43 UTC, Stuard256 commented on src/main/java/com/es/phoneshop/model/product/service/DefaultOrderService.java
> +        } catch (NullPointerException e) {
Если вы про CloneNotSupported Exception, то он требует try catch, а returnить всё равно что-то надо

2021-03-02 20:47 UTC, Stuard256 commented on src/main/java/com/es/phoneshop/model/product/service/DefaultOrderService.java
> +    public Map<String, String> validate(Order order, String firstName, String lastName, String phone, String deliveryDate, String deliveryAdress, String paymentMethod) {
Переделал

2021-03-02 20:50 UTC, Stuard256 commented on src/main/java/com/es/phoneshop/model/product/service/OrderService.java
> +    Map<String,String> validate(Order order, String firstName, String lastName, String phone, String deliveryDate, String deliveryAdress, String paymentMethod);
Переделал

2021-03-02 20:51 UTC, Stuard256 commented on src/main/java/com/es/phoneshop/web/CheckoutPageServlet.java
> +        } else
Добавил

2021-03-06 21:06 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/service/DefaultOrderService.java
> +        } catch (NullPointerException e) {
Не
я про NPE перетекающий магически в EmptyCartException

2021-03-06 21:07 UTC, alexandr-i commented on src/main/java/com/es/phoneshop/model/product/entity/Order.java
> +    public Order() {
Чекни плиз, я всё ещё вижу дефолтный конструктор

2021-03-06 21:17 UTC, alexandr-i approved these changes

2021-03-08 22:05 UTC, alexandr-i approved these changes

2021-03-17 14:31 UTC, merged